name: Profile repo updater

on:
  push:
    branches: [ master ]
  schedule:
    - cron: 0 0 * * MON
    - cron: 0 0 25 2 *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Clone vitalyavolyn/vitalyavolyn
        uses: actions/checkout@v2
        with:
          repository: vitalyavolyn/vitalyavolyn
          token: ${{ github.token }}
          path: userpage

      - name: Install Node.JS
        uses: actions/setup-node@v2-beta

      - name: Install dependencies
        run: yarn --ignore-optional

      - name: Build README.md, index.html
        run: yarn build

      - name: Push README.md to vitalyavolyn/vitalyavolyn
        run: |
          mv _md/README.md userpage
          cd userpage
          git config user.name github-actions
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git diff-index --quiet HEAD || git commit -m "Update README.md"
          git push https://$USERNAME:$REPO_KEY@github.com/vitalyavolyn/vitalyavolyn
        env:
          REPO_KEY: ${{ secrets.REPO_KEY }}
          USERNAME: github-actions[bot]
