name: Profile repo updater

on:
  push:
    branches: [ master ]
  schedule:
    - cron: 0 0 * * MON
    - cron: 0 0 25 2 *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Clone vitalyavolyn/vitalyavolyn
        uses: actions/checkout@v2
        with:
          repository: vitalyavolyn/vitalyavolyn
          token: ${{ secrets.REPO_KEY }}
          path: userpage

      - name: Install Node.JS
        uses: actions/setup-node@v2-beta

      - name: Install dependencies
        run: yarn --ignore-optional

      - name: Build README.md, index.html
        run: yarn build

      - name: Deploy index.html to IPFS
        run: yarn ipfs-deploy _site -p infura -p pinata -d cloudflare
        env:
          IPFS_DEPLOY_PINATA__API_KEY: ${{ secrets.PINATA_API_KEY }}
          IPFS_DEPLOY_PINATA__SECRET_API_KEY: ${{ secrets.PINATA_SECRET_API_KEY }}
          IPFS_DEPLOY_CLOUDFLARE__ZONE: vitalya.me
          IPFS_DEPLOY_CLOUDFLARE__API_EMAIL: i@vitalya.me
          IPFS_DEPLOY_CLOUDFLARE__RECORD: _dnslink.vitalya.me
          IPFS_DEPLOY_CLOUDFLARE__API_KEY: ${{ secrets.CF_API_KEY }}

      - name: Push README.md to vitalyavolyn/vitalyavolyn
        run: |
          mv _md/README.md userpage
          cd userpage
          git config user.name github-actions
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git diff-index --quiet HEAD || git commit -m "Update README.md"
          git push
        env:
          REPO_KEY: ${{ secrets.REPO_KEY }}
